apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: swetha584/frontend:v2
    ports:
    - containerPort: 80
    env:
    - name: NGINX_SERVICE_HOST
      value: "nginx-clusterip-service"  

