apiVersion: v1
kind: Pod
metadata:
  name: my-private-image-pod
  labels:
    app: admin
spec:
  containers:
  - name: nginx
    image: swetha584/frontend-private:latest2
    ports:
    - containerPort: 5173
  imagePullSecrets:
  - name: dockerhub-secret
