apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3  # Number of replicas (pods) to create
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: swetha584/frontend-private:latest2
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume 
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret
